version: 2

sources:
  - name: ecommerce_raw
    schema: ecommerce_raw 
    tables:
    - name: customers
    - name: geolocation
    - name: order_items
    - name: order_payments
    - name: order_reviews
    - name: orders
    - name: product_category_name_translation
    - name: products
    - name: sellers