{{ config(materialized="table") }}

SELECT
    p.PRODUCT_ID AS PRODUCT_ID,
    p.PRODUCT_CATEGORY_NAME AS PRODUCT_CATEGORY_NAME,
    p.PRODUCT_NAME_LENGHT AS PRODUCT_NAME_LENGHT,
    p.PRODUCT_DESCRIPTION_LENGHT AS PRODUCT_DESCRIPTION_LENGHT
FROM {{ ref('products') }} p