version: 2

models:
  - name: dim_time
    description: Dimension de Tiempo
    config:
      schema: service_data_enorb
    columns:
      - name: TIME_ID
        description: Id de la fecha
        tests:
          - unique
          - not_null
      - name: TIME_DATE
        description: Fecha
        tests:
          - unique
          - not_null
      - name: TIME_YEAR
        description: Año
        tests:
          - not_null
      - name: TIME_QUARTER
        description: Cuatrimestre (Q)
        tests:
          - not_null
      - name: TIME_MONTH
        description: Mes
        tests:
          - not_null

  - name: dim_customers
    description: Dimension de clientes
    config:
      schema: service_data_enorb
    columns:
      - name: CUSTOMER_ID
        description: Id del cliente
        tests:        
          - not_null
      - name: CUSTOMER_UNIQUE_ID
        description: Id alternativo del cliente
        tests:        
          - not_null
      - name: CUSTOMER_ZIP_CODE_PREFIX
        description: Prefijo del código zip del cliente
        tests:
          - not_null    
      - name: CUSTOMER_CITY
        description: Ciudad del cliente
        tests:
          - not_null
      - name: CUSTOMER_STATE
        description: Estado del cliente
        tests:
          - not_null
      - name: CUSTOMER_GEO_LAT
        description: Coordenada de latitud del cliente
      - name: CUSTOMER_GEO_LNG
        description: Coordenada de longitud del cliente

  - name: dim_sellers
    description: Dimension de clientes
    config:
      schema: service_data_enorb
    columns:
      - name: SELLER_ID
        description: Id del cliente
        tests:
          - not_null
      - name: SELLER_ZIP_CODE_PREFIX
        description: Prefijo del código zip del cliente
        tests:
          - not_null    
      - name: SELLER_CITY
        description: Ciudad del cliente
        tests:
        - not_null
      - name: SELLER_STATE
        description: Estado del cliente
        tests:
          - not_null
      - name: SELLER_GEO_LAT
        description: Coordenada de latitud del cliente
      - name: SELLER_GEO_LNG
        description: Coordenada de longitud del cliente      

  - name: dim_products
    description: Dimension de productos
    config:
      schema: service_data_enorb
    columns:
      - name: PRODUCT_ID
        description: Id del producto
        tests:
          - unique
          - not_null
      - name: PRODUCT_CATEGORY_NAME
        description: Nombre de la categoría del producto
        tests:
          - not_null
      - name: PRODUCT_NAME_LENGHT
        description: Longitud del nombre del producto           
      - name: PRODUCT_DESCRIPTION_LENGHT
        description: Longitud de la descripción del producto

  - name: dim_order_payments
    description: Dimension con las formas de pago de las ordenes
    config:
      schema: service_data_enorb
    columns:
      - name: ORDER_ID
        description: Id de la orden a la que corresponde el pago de mayor denominación
        tests:
          - not_null
      - name: PAYMENT_SEQUENTIAL
        description: Número secuencial del pago para la orden
        tests:
          - not_null
      - name: PAYMENT_TYPE
        description: Tipo de pago de la orden
        tests:
          - not_null
      - name: PAYMENT_INSTALLMENTS
        description: Cantidad de cuotas del pago
      - name: PAYMENT_VALUE
        description: Monto del pago      

  - name: dim_order_reviews
    description: Reseña de las ordenes
    config:
      schema: service_data_enorb
    columns:
      - name: REVIEW_ID
        description: Id de la reseña de la orden
        tests:
          - not_null      
      - name: ORDER_ID
        description: Id de la orden
        tests:
          - not_null
      - name: REVIEW_SCORE
        description: Puntaje de la reseña
        tests:
          - not_null
      - name: REVIEW_COMMENT_TITLE
        description: Titulo de la reseña
      - name: REVIEW_COMMENT_MESSAGE
        description: Cuerpo de la reseña
      - name: REVIEW_CREATION_DATE
        description: Fecha de creación de la reseña
      - name: REVIEW_ANSWER_TIMESTAMP
        description: Marca de tiempo de la respuesta

  - name: fact_order_items
    description: Datamart de ordenes
    config:
      schema: service_data_enorb
    columns:
      - name: ORDER_ID
        description: Id de la orden
        tests:      
          - not_null              
      - name: CUSTOMER_ID
        description: Id del cliente
        tests:
          - not_null                        
      - name: ORDER_STATUS
        description: Estado de la orden
        tests:
          - not_null
      - name: ORDER_PURCHASE_TIMESTAMP
        description: Marca de tiempo de la orden de compra
        tests:
          - not_null
      - name: ORDER_APPROVED_AT
        description: Fecha de aprobación de la orden
      - name: ORDER_DELIVERED_CARRIER_DATE
        description: Fecha de entrega del pedido al transportista                            
      - name: ORDER_DELIVERED_CUSTOMER_DATE
        description: Fecha de entrega del pedido al cliente                           
      - name: ORDER_ESTIMATED_DELIVERY_DATE
        description: Fecha estimada de entrega del pedido al cliente
        tests:
          - not_null
      - name: ORDER_GROSS_VALUE
        description: Monto bruto de la orden
      - name: ORDER_ITEM_ID
        description: Id del item en la orden
      - name: PRODUCT_ID
        description: Identificador del producto
      - name: SELLER_ID
        description: Identificador del vendedor
      - name: PRICE
        description: Precio del producto
      - name: FREIGHT_VALUE
        description: Costo del flete