{{ config(materialized="table") }}

SELECT
    CUSTOMER_ID
  , CUSTOMER_UNIQUE_ID
  , CAST(CUSTOMER_ZIP_CODE_PREFIX AS INTEGER) AS CUSTOMER_ZIP_CODE_PREFIX
  , TRIM(UPPER(CUSTOMER_CITY)) AS CUSTOMER_CITY
  , TRIM(UPPER(CUSTOMER_STATE)) AS CUSTOMER_STATE
FROM {{ source('ecommerce_raw', 'customers') }}
WHERE CUSTOMER_ID IS NOT NULL