{{ config(materialized="table") }}

SELECT
    CAST(GEOLOCATION_ZIP_CODE_PREFIX AS INTEGER) AS GEOLOCATION_ZIP_CODE_PREFIX
  , GEOLOCATION_LAT
  , GEOLOCATION_LNG
  , TRIM(UPPER(GEOLOCATION_CITY)) AS GEOLOCATION_CITY
  , TRIM(UPPER(GEOLOCATION_STATE)) AS GEOLOCATION_STATE
FROM {{ source('ecommerce_raw', 'geolocation') }}
WHERE GEOLOCATION_ZIP_CODE_PREFIX IS NOT NULL