{{ config(materialized="table") }}

SELECT
    ORDER_ID
  , ORDER_ITEM_ID
  , PRODUCT_ID
  , SELLER_ID
  , CAST(DATE_TRUNC(CAST(SHIPPING_LIMIT_DATE AS DATETIME), DAY) AS DATE) AS SHIPPING_LIMIT_DATE
  , COALESCE(PRICE, 0) AS PRICE
  , COALESCE(FREIGHT_VALUE, 0) AS FREIGHT_VALUE  
FROM {{ source('ecommerce_raw', 'order_items') }}
WHERE ORDER_ID IS NOT NULL AND PRODUCT_ID IS NOT NULL AND SELLER_ID IS NOT NULL