{{ config(materialized="table") }}

SELECT
    REVIEW_ID
  , ORDER_ID
  , REVIEW_SCORE
  , COALESCE(UPPER(TRIM(REVIEW_COMMENT_TITLE)), NULL, 'N/A') AS REVIEW_COMMENT_TITLE
  , COALESCE(UPPER(TRIM(REVIEW_COMMENT_MESSAGE)), NULL, 'N/A') AS REVIEW_COMMENT_MESSAGE
  , CAST(DATE_TRUNC(CAST(REVIEW_CREATION_DATE AS DATETIME), DAY) AS DATE) AS REVIEW_CREATION_DATE
  , CAST(DATE_TRUNC(CAST(REVIEW_ANSWER_TIMESTAMP AS DATETIME), DAY) AS DATE) AS REVIEW_ANSWER_TIMESTAMP  
FROM {{ source('ecommerce_raw', 'order_reviews') }}
WHERE REVIEW_ID IS NOT NULL AND ORDER_ID IS NOT NULL