{{ config(materialized="table") }}

SELECT
    PRODUCT_ID
  , COALESCE (UPPER(TRIM(PRODUCT_CATEGORY_NAME)), 'N/A') AS PRODUCT_CATEGORY_NAME
  , PRODUCT_NAME_LENGHT
  , PRODUCT_DESCRIPTION_LENGHT
  , PRODUCT_PHOTOS_QTY
  , PRODUCT_WEIGHT_G
  , PRODUCT_LENGTH_CM
  , PRODUCT_HEIGHT_CM
  , PRODUCT_WIDTH_CM
FROM {{ source('ecommerce_raw', 'products') }}